services:
  nginx:
    ports:
      - "81:80"
    image: "nginx:latest"
    volumes:
      - ./index.html:/usr/share/nginx/html/tms/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  apache:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./apache.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - nginx